[versions]
lombok = "1.18.42"
jetbrains_annotations = "26.0.2"

spock_core = "2.4-groovy-5.0"
byte_buddy = "1.18.2"
mockito_core = "5.21.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }

spock_core = { module = "org.spockframework:spock-core", version.ref = "spock_core" }
byte_buddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byte_buddy" }
mockito_core = { module = "org.mockito:mockito-core", version.ref = "mockito_core" }

[bundles]
annotations = ["lombok", "jetbrains_annotations"]

test_framework = ["spock_core", "byte_buddy", "mockito_core"]
